### ISSUE TITLE
How do you disable SSL certificate checking?

### ISSUE THREAD

**Issue by glenc2004** [AstroMatt/atlassian-python-api#15]
Hi. I like your python api frontend. One question though. How do you disable SSL certificate checking. Do you have a value that can be set that's passed onto the request module?

Thanks!

Glen Collins

**Comment by cattz** [comment]
I've added a parameter to allow setting up a client not to verify SSL certs:

    bamboo = Bamboo(..., verify_ssl=False)

This parameter is passed to every `session.request` as `verify` parameter. As per requests docstring:

>       :param verify: (optional) Either a boolean, in which case it controls whether we verify
>        the server's TLS certificate, or a string, in which case it must be a path
>        to a CA bundle to use. Defaults to ``True``.
