### ISSUE TITLE
jira-project-leaders.py

### ISSUE THREAD

**Issue by KrzysztofSkotnicki** [AstroMatt/atlassian-python-api#32]
Cześć Matt,

Mam problem po uruchomieniu: jira-project-leaders.py
Jeżeli lider projektu ma login zawierający myślnik to skrypt się nie wykonuje. (np. admini-warszawa)
Wygląda na to że trzeba coś poprawić w jira,py

`    def project_leaders(self):
        for project in self.projects():
            key = project['key']
            project_data = self.project(key)
            lead = self.user(project_data['lead']['key'])
            yield {
                'project_key': key,
                'project_name': project['name'],
                'lead_name': lead['displayName'],
                'lead_key': lead['key'],
                'lead_email': lead['emailAddress']}`

z góry dzięki za pomoc

**Comment by KrzysztofSkotnicki** [comment]
Przepraszam ale powyższe jednak nieaktualne - loginy z myślnikami nie stanowią problemu.
Problem pojawia się w momencie kiedy login zostanie zmieniony na inny.
1. Dodałem usera:  opel-astra
2. Dodałem go jako lidera
3. skrypt zadziałał poprawnie - wypisał tego usera
4. w zarządzaniu zmieniłem login tego samego usera na:  opel-astra2
5. dodałem tego nowego usera w projekcie raz jeszcze
6. wykonałem reidnex 
7. uruchamiam skrypt i pojawai się bład w momencie pobierania danych z tego właśnie projektu:

`{'errorMessages': ["The user named 'opel-astra' does not exist"], 'errors': {}}
Traceback (most recent call last):`

skąd on pobiera tego usera - skoro już go nie ma? powinien być opel-astra2

**Comment by AstroMatt** [comment]
Ciekawe, nie mam zielonego pojęcia czemu tak działa.
Może to jakieś cache'owanie API Jiry.
Trzeba się temu bardziej pjrzeć

**Comment by KrzysztofSkotnicki** [comment]
Wydaje mi się że mam trop:
API dla projektu w którym user zmienił nazwę: api/2/project/{projectIdOrKey}

  "lead": {
    "self": "https://jira.grupawp.pl/rest/api/2/user?username=admini-monitoring",
    **"key": "monitoring",**
    "name": "admini-monitoring",

fragment jira.py

    def project_leaders(self):
        for project in self.projects():
            key = project['key']
            project_data = self.project(key)
            lead = self.user(project_data['lead']['**key**'])
            yield {
                'project_key': key,
                'project_name': project['name'],
                'lead_name': lead['displayName'],
                'lead_key': lead['**key**'],
                'lead_email': lead['emailAddress']}

Może zamiast "key" trzeba dać "name"  ?

**Comment by KrzysztofSkotnicki** [comment]
Zmieniłem w jiry.py 

    def project_leaders(self):
        for project in self.projects():
            key = project['key']
            project_data = self.project(key)
            lead = self.user(project_data['lead']['name'])
            yield {
                'project_key': key,
                'project_name': project['name'],
                'lead_name': lead['displayName'],
                'lead_key': lead['name'],
                'lead_email': lead['emailAddress']}

test przebiegł prawidłowo

**Comment by AstroMatt** [comment]
ciekawe czemu to tak było, jakaś pomyłka.
Jak zrobisz Pull Requesta to z największą przyjemnością zmerguję :)

**Comment by KrzysztofSkotnicki** [comment]
tak też zrobiłem :)
