### ISSUE TITLE
title passed as body in self.create_page

### ISSUE THREAD

**Issue by ope-carbon** [AstroMatt/atlassian-python-api#38]
this line in Confluence.update_or_create
```
result = self.create_page(space, parent_id, title, body)
````
should be 
```
result = self.create_page(space=space, parent_id=parent_id, title=title, body=body)
```
because
```
def create_page(self, space, title, body, parent_id = None, type='page')
``` 
as it currently is, parent_id get passed in as title, title as body etc. 
I am free to submit a PR to fix this right? Working on it.

**Comment by opethe1st** [comment]
Raised a PR here - https://github.com/AstroMatt/atlassian-python-api/issues/38

**Comment by ope-carbon** [comment]
fixed!
