### ISSUE TITLE
Creating pages with markdown?

### ISSUE THREAD

**Issue by chaosblog** [AstroMatt/atlassian-python-api#64]
Is there a way to use create a page in Confluence with create_page(), which has Confluence Markdown enabled?

**Comment by gonchik** [comment]
Hi! 

you can do in 2 step:
1. Convert into confluence storage format your markdown
https://github.com/AstroMatt/atlassian-python-api/blob/master/atlassian/confluence.py#L374
2. Then use method update_or_create_page()
https://github.com/AstroMatt/atlassian-python-api/blob/master/atlassian/confluence.py#L352

Hope it helps. 
If you have other idea feel free to share it :)

Cheers,
Gonchik Tsymzhitov

**Comment by chaosblog** [comment]
Thanks. That's what I was looking for.
