### ISSUE TITLE
Getting oops you have found dead link while creating and reading page

### ISSUE THREAD

**Issue by keshrisohit** [AstroMatt/atlassian-python-api#69]
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Oops, you&#39;ve found a dead link. - JIRA</title><script type="text/javascript">contextPath = "";</script><link type='text/css' rel='stylesheet' href='/static-assets/metal-all.css' media='all'><script src='/static-assets/metal-all.js'></script><meta name="decorator" content="none" /></head><body class=" error-page error404"><script type="text/javascript">document.body.className += " js-enabled";</script><div id="page"><header id="header" role="banner"></header><section id="content" role="main"><div class="aui-page-panel"><div class="aui-page-panel-inner"><section class="aui-page-panel-content lowerContent"><div id="error-state"><span class="error-type"></span><h1>Oops, you&#39;ve found a dead link.</h1><ul><li>Go back to the <a href="javascript:window.history.back()">previous page</a></li><li>Go to the <a href="/secure/MyJiraHome.jspa">Home Page</a></li></ul></div></section></div></div></section><footer id="footer" role="contentinfo"><section class="footer-body">

<ul class="atlassian-footer">
    <li>
        Atlassian JIRA <a class="seo-link" href="https://www.atlassian.com/software/jira">Project Management Software</a>

**Comment by gonchik** [comment]
Hi! 

How do you get this error? 

Thanks 
Gonchik Tsymzhitov

**Comment by keshrisohit** [comment]
we were missing to add /wiki at the end of root_url.Thanks @gonchik for quick response.
